version: '3.5'

services:

  fileinspector:
    logging:
      driver: fluentd
      options:
          fluentd-address: localhost:24224
          fluentd-async-connect: 'true'
          fluentd-retry-wait: '1s'
          fluentd-max-retries: '30'
          tag: fileinspector

  frontend:
    logging:
        driver: fluentd
        options:
            fluentd-address: localhost:24224
            fluentd-async-connect: 'true'
            fluentd-retry-wait: '1s'
            fluentd-max-retries: '30'
            tag: frontend
      
  backend:
    logging:
        driver: fluentd
        options:
            fluentd-address: localhost:24224
            fluentd-async-connect: 'true'
            fluentd-retry-wait: '1s'
            fluentd-max-retries: '30'
            tag: backend
      
      
#  elasticsearch:
#    logging:
#      driver: fluentd
#      options:
#          fluentd-address: localhost:24224
#          fluentd-async-connect: 'true'
#          fluentd-retry-wait: '1s'
#          fluentd-max-retries: '30'
#          tag: elasticsearch

  mongo:
    logging:
      driver: fluentd
      options:
          fluentd-address: localhost:24224
          fluentd-async-connect: 'true'
          fluentd-retry-wait: '1s'
          fluentd-max-retries: '30'
          tag: mongoDB
    
  mongo-admin:
    logging:
      driver: fluentd
      options:
          fluentd-address: localhost:24224
          fluentd-async-connect: 'true'
          fluentd-retry-wait: '1s'
          fluentd-max-retries: '30'
          tag: mongo-admin
  
    
