version: '3.5'

services:
  fileinspector:
    env_file: 
      - DEV.env
    ports:
      - "8080:8080"
    volumes:
      - 'C:/data:/html'
    networks:
      - internal-network
      
  frontend:
    networks:
      - internal-network
    ports: 
      - '80:4200'
    env_file: 
      - DEV.env
##    volumes:
##      - './frontend:/usr/src/app'
    command: > 
      bash -c "ng serve --host 0.0.0.0 --port 4200"
      
  express:
    networks:
      - internal-network
    env_file: 
      - DEV.env
##    volumes:
##      - './backend:/usr/src/app' 
    ports: 
      - '3000:3000'
    command: > 
      bash -c "npm start --host 3000 --port 3000"
      
  fluentd:
    networks:
      - internal-network
    env_file: 
      - DEV.env
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - 24224:24224
      
  elasticsearch:
    networks:
      - internal-network
    env_file: 
      - DEV.env
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      
  kibana:
    networks:
      - internal-network
    env_file: 
      - DEV.env
    ports:
      - "5601:5601"
      
  kibana-cfg:
    networks:
      - internal-network
    env_file: 
      - DEV.env
    depends_on:
      - kibana
      
  mongo:
    networks:
      - internal-network
    env_file: 
      - DEV.env
    ports:
      - "27017:27017"
      
      
  mongo-express:
    networks:
      - internal-network
    env_file: 
      - DEV.env
    ports:
      - 8081:8081
    depends_on:
      - mongo   
      
