version: '3.5'

services:
 
  fluentd:
    build:
      context: ./fluentd
    image: fluentd:1.0
      
  elasticsearch:
    build:
      context: ./elasticsearch
    image: elasticsearch:1.0 
      
  kibana:
    build:
      context: ./kibana
    image: kibana:1.0
    depends_on:
      - elasticsearch
      - fluentd
      - kibana

  kibana-cfg:
    build:
      context: ./kibana-cfg
    image: kibana-cfg:1.0
    links: 
      - kibana
    depends_on:
      - elasticsearch
      - fluentd
      - kibana

  mongo:
    build:
      context: ./mongodb
    image: mongo:1.0
    volumes:
      - mongodata:/data/db
    depends_on:
      - elasticsearch
      - fluentd
      - kibana


  mongo-admin:
    image: mongo-express
    depends_on:
      - mongo

  backend:
    build:
      context: ./backend
    image: backend:1.0
    depends_on:
      - elasticsearch
      - fluentd
      - kibana
      - mongo

  frontend:
    build:
      context: ./frontend
    image: frontend:1.0
    depends_on:
      - elasticsearch
      - fluentd
      - kibana
      - backend

  fileinspector:
    build:
      context: ./FileWebInspector
    image: fileinspector:1.0

      
      


networks:
  internal-network:
  
volumes:
  mongodata:
 