version: '3.5'
services:
  fileinspector:
    build: ./FileWebInspector/
    image: fileinspector:1.0
    ports:
      - "8080:8080"
    volumes:
      - 'c:/data:/html'
  admin-console:
    build: ./adminConsole
    image: admin-console:1.0
    logging:
      driver: "fluentd"
      options:
        tag: adminConsole
    networks:
      - internal-network
    volumes:
      - './adminConsole:/usr/src/app'
    deploy:
      replicas: 1
    ports: 
      - '80:4200'
    command: > 
      bash -c "ng serve --host 0.0.0.0 --port 4200"
  express:
    networks:
      - internal-network
    build: ./backend
    image: backend:1.0
    logging:
      driver: "fluentd"
      options:
        tag: backend
    deploy:
      replicas: 1
    volumes:
      - './backend:/usr/src/app' 
    ports: 
      - '3000:3000'
    command: > 
      bash -c "npm start --host 0.0.0.0 --port 3000"
  fluentd:
    build: ./logSystem
    image: logSystem:1.0
    volumes:
      - ./log:/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - internal-network
    deploy:
      restart_policy:
           condition: on-failure
           delay: 20s
           max_attempts: 3
           window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s
      

networks:
  internal-network: