version: '3.5'

services:
  fileinspector:
    build:
      context: ./FileWebInspector
    image: fileinspector:1.0

  frontend:
    build:
      context: ./frontend
    image: frontend:1.0
    depends_on:
      - fluentd      
      
  express:
    build:
      context: ./backend
    image: backend:1.0
      
  fluentd:
    build:
      context: ./fluentd
    image: fluentd:1.0
    depends_on:
      - kibana
      
  elasticsearch:
    build:
      context: ./elasticsearch
    image: elasticsearch:1.0 
      
  kibana:
    build:
      context: ./kibana
    image: kibana:1.0

  kibana-cfg:
    build:
      context: ./kibana-cfg
    image: kibana-cfg:1.0
    depends_on: 
      - kibana

  mongo:
    build:
      context: ./mongodb
    image: mongo:1.0
    depends_on:
      - fluentd
    
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo