version: '3.8'

services:
 
  mongo:
    build:
      context: ../mongodb
    image: mongo:1.0    

  mongo-admin:
    image: mongo-express
    
  backend:
    build:
      context: ../backend
    image: backend:1.0
      
  frontend:
    build:
      context: ../frontend
    image: frontend:1.0

